OBJDIR = build
SHLIB_EXT = do
SHLIB_FLAGS = -fPIC -shared

CFLAGS += -Wall -O3 -ffast-math -march=native -fcx-limited-range -fno-exceptions -fPIC -larmadillo -lopenblas -llapack
CXXFlAGS += -Wall -O3 -ffast-math -march=native -fcx-limited-range -fno-exceptions -fPIC -larmadillo -lopenblas -llapack
LA_LIBS = -O3 -ffast-math -lopenblas -llapack
ARMA_LIBS = -larmadillo

LUA_INC = -I/usr/local/include
LUA_LIB = -llua -ldl