OBJDIR = build
SHLIB_EXT = dll
SHLIB_FLAGS = -fpic -shared

CFLAGS   += -O3 -Wall -march=native -fcx-limited-range -static
CXXFLAGS += -std=c++11 -O3 -Wall -march=native -fcx-limited-range

LA_LIBS = -L$(HOME)/code/OpenBLAS -lopenblas_haswell-r0.2.16.dev -lgfortran -lquadmath

LUA_INC = 
LUA_LIB = -Wl,-Bdynamic -llua -Wl,-Bstatic
LUA_MODULE_LIB = -DLUA_BUILD_AS_DLL -Wl,-Bdynamic -llua.dll -Wl,-Bstatic