#define AUTHOR "Kaifeng Chen"
#define PACKAGE "MESH"
#define PACKAGE_BUGREPORT "kfchen@stanford.edu"
#define PACKAGE_NAME "MESH"
#define PACKAGE_STRING "MESH 1.0.3"
#define PACKAGE_TARNAME "MESH"
#define PACKAGE_URL ""
#define PACKAGE_VERSION "1.0.3"
#define VERSION "1.0.3"
